apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: react-app
        image: amnes/test-app:latest
        ports:
        - containerPort: 5000